name: build-linux

on:
  push:
    branches: [ "dev" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    if:  startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true  # This tells checkout action to clone submodules
          token: ${{ secrets.GH_PAT }}  # Personal Access Token with repo scope


    - name: pull
      run: git submodule update --init --recursive


    - name: install 
      run: |
        sudo apt install libsqlite3-dev libncurses5-dev python3 wget
        wget https://download.swift.org/swift-6.0.2-release/ubuntu2204/swift-6.0.2-RELEASE/swift-6.0.2-RELEASE-ubuntu22.04.tar.gz
        tar -xvzf swift-6.0.2-RELEASE-ubuntu22.04.tar.gz

    - name: Build
      run:  |
        export root=$(pwd)/swift-6.0.2-RELEASE-ubuntu22.04
        $root/usr/bin/swift build -Xcxx -I$root/usr/lib/swift -Xcxx -I$root/usr/lib/swift/Block -c release
      
      
      
    - name: Check if release exists
      id: check_release
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
        if gh release view ${{ github.ref_name }} 2>&1; then
            echo "release_exists=true" >> $env:GITHUB_OUTPUT
        else
            echo "release_exists=false" >> $env:GITHUB_OUTPUT
        fi
        else
        if gh release view ${{ github.ref_name }} &> /dev/null; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
        else
            echo "release_exists=false" >> $GITHUB_OUTPUT
        fi
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.RTOKEN}}

        
    - name: Create Release
      id: create_release
      if: steps.check_release.outputs.release_exists == 'false' && startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RTOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Get Release Upload URL
      id: get_upload_url
      shell: bash
      run: |
        upload_url=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .upload_url)
        echo $upload_url
        if [[ $upload_url == "" ]]; then 
            echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
        else
            echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
        fi
        # echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
        # echo "upload_url=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .upload_url)" >> $GITHUB_OUTPUT
        # if [ "${{ steps.check_release.outputs.release_exists }}" == "true" ]; then
            # echo "upload_url=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .upload_url)" >> $GITHUB_OUTPUT
        # else
            # echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
        # fi
      env:
        GITHUB_TOKEN: ${{ secrets.RTOKEN }}






    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RTOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
        asset_path: ./.build/release/sourcekit-lsp
        asset_name: sourcekit-lsp-amd64-linux
        asset_content_type: application/octet-stream





        
